
import plotly.express as px, pandas as pd
from jinja2 import Template
from utils import safe_str

def make_plot_html(df, x, y, ctype, theme='light'):
    # simple wrapper to create plotly inline HTML (keeps app independent)
    try:
        if ctype == 'table':
            cols = y if isinstance(y, list) else [c for c in [x,y] if c in df.columns]
            return df[cols].head(40).to_html(index=False)
        if ctype in ('bar','line','area'):
            agg = df.groupby(x)[y].sum(numeric_only=True).reset_index()
        else:
            agg = df
        if ctype == 'bar': fig = px.bar(agg, x=x, y=y)
        elif ctype == 'line': fig = px.line(agg, x=x, y=y)
        elif ctype == 'area': fig = px.area(agg, x=x, y=y)
        elif ctype == 'donut': fig = px.pie(agg, names=x, values=y, hole=0.45)
        elif ctype == 'scatter': fig = px.scatter(df, x=x, y=y)
        elif ctype == 'hist': fig = px.histogram(df, x=y)
        else: fig = px.bar(agg, x=x, y=y)
        fig.update_layout(margin=dict(l=8,r=8,t=36,b=8), height=380)
        return fig.to_html(include_plotlyjs='cdn', full_html=False)
    except Exception as e:
        return f"<div style='color:#c00'>Plot error: {safe_str(e)}</div>"

TEMPLATE = Template("""<!doctype html><html><head><meta charset='utf-8'/><meta name='viewport' content='width=device-width,initial-scale=1'/><title>{{ title }}</title><style>
:root{--pb-bg:#fff;--pb-panel:#f7f8fa;--pb-border:#d0d3d9;--pb-ink:#242424;--pb-muted:#606060;--pb-radius:10px;--pb-shadow:0 2px 10px rgba(2,6,23,0.06);}
body{background:var(--pb-panel);font-family:Segoe UI,Arial,sans-serif;margin:0;color:var(--pb-ink)}.wrapper{max-width:1480px;margin:auto;padding:18px}.dashboard{background:var(--pb-bg);border:1px solid var(--pb-border);border-radius:var(--pb-radius);box-shadow:var(--pb-shadow);padding:18px;aspect-ratio:16/9;display:flex;flex-direction:column;gap:18px;overflow:hidden}.header{display:flex;justify-content:space-between;align-items:center}.kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px}.kpi-card{background:white;border-radius:8px;border:1px solid var(--pb-border);padding:12px;min-height:64px;display:flex;flex-direction:column;justify-content:center;box-shadow:0 1px 4px rgba(0,0,0,0.03)}.kpi-title{font-size:12px;color:var(--pb-muted)}.kpi-value{font-size:22px;font-weight:700;margin-top:6px}.viz-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(420px,1fr));gap:18px;align-items:start}.viz{background:white;padding:12px;border-radius:8px;border:1px solid var(--pb-border);min-height:420px;display:flex;flex-direction:column;box-shadow:0 2px 8px rgba(0,0,0,0.04);overflow:hidden}.viz-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}.viz-title{font-size:14px;color:var(--pb-ink)}.viz-type{font-size:12px;color:var(--pb-muted);background:var(--pb-panel);padding:4px 8px;border-radius:6px;border:1px solid var(--pb-border)}.insight{margin-top:12px;font-size:13px;color:var(--pb-muted)}.footer{text-align:right;font-size:12px;color:var(--pb-muted);margin-top:auto}</style></head><body><div class='wrapper'><div class='dashboard'><div class='header'><h2>{{ title }}</h2><div class='meta'>Auto-BI • 16:9 • Theme: {{ theme }}</div></div><div class='kpis'>{{ kpis|safe }}</div>{{ sections|safe }}<div class='footer'>Generated by Auto-BI • Story: Overview → Performance → Trends → Deep Dive → Risks</div></div></div></body></html>""")

def build_dashboard_html(spec, df):
    kpis = spec.get('kpis', [])
    sections = spec.get('sections', [])
    kpi_html = ''
    for k in kpis:
        title = safe_str(k.get('title')); expr = k.get('expr','COUNT(*)'); fmt = k.get('format','auto')
        val = 0
        try:
            if expr.upper().startswith('SUM('): col = expr[4:-1]; val = df[col].sum()
            elif expr.upper().startswith('AVG('): col = expr[4:-1]; val = df[col].mean()
            elif expr.upper().startswith('COUNT('): col = expr[6:-1]; val = df[col].count()
        except:
            val = 0
        kpi_html += f"<div class='kpi-card'><div class='kpi-title'>{title}</div><div class='kpi-value'>{val}</div></div>"
    sections_html = ''
    for sec in sections:
        sec_name = safe_str(sec.get('name','Section')); viz_block = ''
        for ch in sec.get('charts', []):
            ctype = ch.get('type','bar'); x = ch.get('x'); y = ch.get('y')
            html_piece = make_plot_html(df, x or '', y or '', ctype, theme=spec.get('theme','light'))
            narrative = sec.get('narrative','') or ''
            viz_block += f"<div class='viz'><div class='viz-head'><div class='viz-title'>{safe_str(x)} vs {safe_str(y)}</div><div class='viz-type'>{safe_str(ctype)}</div></div>{html_piece}<div class='insight'>🧠 {safe_str(narrative)}</div></div>"
        if viz_block:
            sections_html += f"<section><h3>{sec_name}</h3><div class='viz-grid'>{viz_block}</div></section>"
    html = TEMPLATE.render(title=safe_str(spec.get('title','Dashboard')), theme=spec.get('theme','light'), kpis=kpi_html, sections=sections_html)
    return html

def render_preview(html, height=800):
    import streamlit as st
    st.components.v1.html(html, height=height, scrolling=True)

def make_explainability_table(spec, df):
    rows = []
    for sec in spec.get('sections', []):
        for ch in sec.get('charts', []):
            x = ch.get('x'); y = ch.get('y'); ctype = ch.get('type', 'bar')
            rows.append({'section': sec.get('name'), 'x': x, 'y': y, 'type': ctype})
    return pd.DataFrame(rows)
